import Head from 'next/head'
import Header from '/components/header'
import Footer from '/components/footer'

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container mx-auto my-10">{children}</main>
      <Footer />
    </>
  )
}
